/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mcxiaoke_ndk_Native */

#ifndef _Included_com_mcxiaoke_ndk_Native
#define _Included_com_mcxiaoke_ndk_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mcxiaoke_ndk_Native
 * Method:    debugInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mcxiaoke_ndk_Native_debugInfo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
